### ISSUE TITLE
Dates should be represented in a human readable format

### ISSUE THREAD

**Issue by reynoldsm88** [WorldModelers/DART#1]

**Comment by kwalcock** [comment]
This seems to have been taken care of in the meantime.  However, I'll let someone else close it.

**Comment by kwalcock** [comment]
The integer 0 which was previously used to indicate absence of a date was changed to the start of the epoch, "1970-01-01", which looks too much like a real date.  JSON rules require null for a string that doesn't exist.  Alternatively, the key of CreationDate or ModDate could be removed.

**Comment by reynoldsm88** [comment]
@kwalcock I'm going to close this issue again and we can track the new error here: https://github.com/WorldModelers/DART/issues/14
