### ISSUE TITLE
Document 8e85eba8fd2b5fd607142ce0a6e5ffdf has no extracted text

### ISSUE THREAD

**Issue by kwalcock** [WorldModelers/DART#12]
The metadata is returned in an elasticsearch, but the extracted text is not in the record.  The file is not in the zip collection.  I am not able to look at the raw file to see what might be wrong.

**Comment by yanzv** [comment]
@kwalcock 8e85eba8fd2b5fd607142ce0a6e5ffdf.pdf is an image scan of a document which is excluded from extraction of text at this time.

**Comment by kwalcock** [comment]
Thanks for checking.  I've mapped the extracted text to "" if the value is missing.

**Comment by yanzv** [comment]
@kwalcock Thanks for the update.  Can you please close the issue.
